###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "name": "Aristóteles", 
    "email": "Aristóteles@gmail.com" ,
    "password": "217y371$23gyd",
    "role": "ADMIN"
}


###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "Aristóteles@gmail.com",
    "password": "217y371$23gyd"
}